name: Build
on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                os: [macos-12, windows-2022]

        runs-on: ${{ matrix.os }}
        name: Build on ${{ matrix.os }}
        steps:
            - name: Checkout current commit/branch/tag
              uses: actions/checkout@v3

            - name: Setup Node 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: yarn install

            - name: Lint TypeScript files
              run: yarn lint

            - name: Run tests
              run: yarn test

            - name: Bundle files
              run: yarn bundle
              env:
                  NODE_ENV: production

            - name: Publish new release
              if: startsWith(github.ref, 'refs/tags')
              run: yarn package:publish
              env:
                  CI: true
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
